//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustSA.EnityFrameWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JustSAEntities : DbContext
    {
        public JustSAEntities()
            : base("name=JustSAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataLog> DataLog { get; set; }
        public virtual DbSet<DataLookUp> DataLookUp { get; set; }
        public virtual DbSet<SportMembers> SportMembers { get; set; }
    
        public virtual ObjectResult<GetAllSportMemberDetail_Result> GetAllSportMemberDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllSportMemberDetail_Result>("GetAllSportMemberDetail");
        }
    }
}
